# Generated by Django 4.2.11 on 2024-04-19 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_language_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book", old_name="book", new_name="language",
        ),
    ]
